ARG APP_NAME=notify-service-api
## Build from demos/mco/ops/Dockerfile
## docker build -t nzuguem/java-runtime:21.0.5_11-jre -f demos/mco/ops/Dockerfile --push .
FROM nzuguem/java-runtime:21.0.5_11-jre
