FROM eclipse-temurin:21 AS extracted

WORKDIR /application

COPY target/notify-service-api.jar ./app.jar

RUN <<EOF
java -Djarmode=tools -jar app.jar extract --destination extracted
EOF


FROM nzuguem/java-runtime:21.0.5_11-jre

COPY --from=extracted /application/extracted/lib ./lib
COPY --from=extracted /application/extracted/app.jar ./